# Generated by Django 3.2.7 on 2023-01-10 17:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response',
            field=jsonfield.fields.JSONField(),
        ),
    ]
