version: "3.3"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - quiz-static-data:/vol/web/static
      - quiz-media-data:/vol/web/media
    environment:
      - ALLOWED_HOSTS=127.0.0.1
      - DEBUG=1

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - quiz-static-data:/vol/static
      - quiz-media-data:/vol/media

volumes:
  quiz-static-data:
  quiz-media-data:
